### ISSUE TITLE
Vangelis review

### ISSUE THREAD

**Issue by vangelif** [momo-87/my-porfolio-project#28]
Overall you did a great job with your portfolio.

I loved the background interactive UI. However there are a few things you might want to consider:

1/ Font size -> you could increase them
![image](https://github.com/momo-87/my-porfolio-project/assets/119002288/b34ee388-f305-4412-8c15-4bb007f085ab)

2/ Finalize the text here
![image](https://github.com/momo-87/my-porfolio-project/assets/119002288/4f12ff43-173c-4e93-9e29-07ddaa95aa1f)

3/ Increase icons size
![image](https://github.com/momo-87/my-porfolio-project/assets/119002288/0125fd84-e100-4890-9491-0be1e264b438)

4/ similarly with social media icons
![image](https://github.com/momo-87/my-porfolio-project/assets/119002288/debe5b95-5571-49b7-a623-6f9717786951)

5/ align to the right the close button in modal. Make sure that image is not overstretching too much on the edges
![image](https://github.com/momo-87/my-porfolio-project/assets/119002288/5d5c96c8-22fa-4dc2-9180-f4d99dbc01b0)

6/ can re-do the overlap of the images
![image](https://github.com/momo-87/my-porfolio-project/assets/119002288/48d50377-bc9d-4ae5-a080-67cc66295512)

**Comment by momo-87** [comment]
Thank you Vangelis for your feedback. Your suggestions are all pertinent and I consider them.
